name: Deploy MkDocs Site to GitHub Pages

on:
  push:
    branches:
      - main  # Ana branch (eğer farklı bir branch kullanıyorsan, bunu değiştir)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # İhtiyacınıza göre Python sürümünü belirleyebilirsiniz.
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs  # MkDocs yükle
        pip install mkdocs-material  # Eğer `material` tema kullanıyorsan, bunu da ekle.
        
    - name: Build the site
      run: mkdocs build  # MkDocs site build işlemi
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Otomatik token kullanımı
        publish_dir: ./site  # MkDocs'un build ettiği site dosyaları burada olur
